# =============================================================================
#                    FLASH-LAG EFFECT (FLE) E2 ANALYSIS
#                         Last modified: January 14, 2026
# =============================================================================
#
# This script analyzes data from Experiment 2 (FLE Baseline Decomposition)
# Calculates mean reported positions and derived measures for each condition.
#
# INPUT: CSV files generated by FLE_E2.m
# OUTPUT: Wide-format CSV with mean offsets for all conditions and derived measures
#
# EXPERIMENTAL CONDITIONS:
#   1. flashbaseline    - Flash alone → baseline flash bias
#   2. motionbaseline   - Motion with fixation cue → baseline motion bias
#   3. flash_motion     - Localize flash with motion present
#   4. motion_flash     - Localize motion with flash present
#
# KEY EQUATIONS:
#   FLE_raw(petal/fugal) = PSE_motion_flash - PSE_flash_motion
#   FLE_corr(petal/fugal) = [PSE_motion_flash - PSE_motionbaseline] - 
#                           [PSE_flash_motion - PSE_flashbaseline]
#   ΔFLE_raw = FLE_raw(petal) - FLE_raw(fugal)
#   ΔFLE_corr = FLE_corr(petal) - FLE_corr(fugal)
#
# Sign convention: Negative values = foveal displacement

# =============================================================================
#                              LOAD LIBRARIES
# =============================================================================

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)

# =============================================================================
#                           CONFIGURATION
# =============================================================================

# Specify the directory containing CSV files
data_dir <- "/Users/jmar3294/Desktop/E2_2026_FLE/EXPERIMENT 2 (JAN 2026)/E2 DATA"

# =============================================================================
#                        HELPER FUNCTIONS
# =============================================================================

# Function to calculate mean and SE for a condition
calc_summary <- function(data) {
  data %>%
    summarise(
      mean_offset = mean(foveal_offset, na.rm = TRUE),
      se_offset = sd(foveal_offset, na.rm = TRUE) / sqrt(n()),
      n_trials = n(),
      n_valid = sum(valid == "valid"),
      .groups = 'drop'
    )
}

# Standard error function
ste <- function(x) {
  sd(x, na.rm = TRUE) / sqrt(sum(!is.na(x)))
}

# =============================================================================
#                          READ AND PROCESS DATA
# =============================================================================

# List all CSV files matching the pattern
csv_files <- list.files(
  path = data_dir,
  pattern = "^\\d{3}_FLE_E2_.*\\.csv$",
  full.names = TRUE
)

if (length(csv_files) == 0) {
  stop("No CSV files found in the specified directory!")
}

cat(sprintf("Found %d data files\n", length(csv_files)))

# Initialize list to store participant data
participant_list <- list()

# Loop through each CSV file
for (file_path in csv_files) {
  
  # Extract subject ID from filename
  filename <- basename(file_path)
  subject_id <- substr(filename, 1, 3)
  
  cat(sprintf("Processing subject %s...\n", subject_id))
  
  # Read the data
  data <- read_csv(file_path, show_col_types = FALSE)
  
  # Filter valid trials only
  data_valid <- data %>%
    filter(valid == "valid")
  
  cat(sprintf("  Valid trials: %d / %d\n", nrow(data_valid), nrow(data)))
  
  # Calculate mean offset for each condition × motion direction × hemifield
  # Hemifield: upper (upper_left, upper_right) vs lower (lower_left, lower_right)
  
  data_valid <- data_valid %>%
    mutate(
      hemifield = case_when(
        quadrant %in% c("upper_left", "upper_right") ~ "upper",
        quadrant %in% c("lower_left", "lower_right") ~ "lower",
        TRUE ~ NA_character_
      )
    )
  
  # Calculate PSEs for each condition
  pse_summary <- data_valid %>%
    group_by(condition, motion_direction, hemifield) %>%
    calc_summary()
  
  # Pivot to wide format for easier calculations
  pse_wide <- pse_summary %>%
    mutate(
      condition_motion = paste(condition, motion_direction, hemifield, sep = "_")
    ) %>%
    select(condition_motion, mean_offset, n_valid) %>%
    pivot_wider(
      names_from = condition_motion,
      values_from = c(mean_offset, n_valid),
      names_sep = "."
    )
  
  # Add subject ID
  pse_wide$subject_id <- subject_id
  
  # Calculate derived measures for each hemifield
  for (hemi in c("upper", "lower")) {
    
    # Get PSE values (handle missing conditions gracefully)
    get_pse <- function(cond, motion) {
      col_name <- paste0("mean_offset.", cond, "_", motion, "_", hemi)
      if (col_name %in% names(pse_wide)) {
        return(pse_wide[[col_name]])
      } else {
        return(NA)
      }
    }
    
    # Flash baseline (no motion)
    pse_flashbaseline <- get_pse("flashbaseline", "none")
    
    # Motion baseline (petal and fugal)
    pse_motionbaseline_petal <- get_pse("motionbaseline", "petal")
    pse_motionbaseline_fugal <- get_pse("motionbaseline", "fugal")
    
    # Flash|motion (petal and fugal)
    pse_flash_motion_petal <- get_pse("flash_motion", "petal")
    pse_flash_motion_fugal <- get_pse("flash_motion", "fugal")
    
    # Motion|flash (petal and fugal)
    pse_motion_flash_petal <- get_pse("motion_flash", "petal")
    pse_motion_flash_fugal <- get_pse("motion_flash", "fugal")
    
    # Calculate raw FLE
    # FLE_raw = PSE_motion_flash - PSE_flash_motion
    pse_wide[[paste0("FLE_raw_petal_", hemi)]] <- pse_motion_flash_petal - pse_flash_motion_petal
    pse_wide[[paste0("FLE_raw_fugal_", hemi)]] <- pse_motion_flash_fugal - pse_flash_motion_fugal
    
    # Calculate corrected FLE
    # FLE_corr = [PSE_motion_flash - PSE_motionbaseline] - [PSE_flash_motion - PSE_flashbaseline]
    motion_component_petal <- pse_motion_flash_petal - pse_motionbaseline_petal
    flash_component_petal <- pse_flash_motion_petal - pse_flashbaseline
    pse_wide[[paste0("FLE_corr_petal_", hemi)]] <- motion_component_petal - flash_component_petal
    
    motion_component_fugal <- pse_motion_flash_fugal - pse_motionbaseline_fugal
    flash_component_fugal <- pse_flash_motion_fugal - pse_flashbaseline
    pse_wide[[paste0("FLE_corr_fugal_", hemi)]] <- motion_component_fugal - flash_component_fugal
    
    # Calculate asymmetry (delta)
    # ΔFLE = FLE(petal) - FLE(fugal)
    pse_wide[[paste0("delta_FLE_raw_", hemi)]] <- 
      pse_wide[[paste0("FLE_raw_petal_", hemi)]] - pse_wide[[paste0("FLE_raw_fugal_", hemi)]]
    
    pse_wide[[paste0("delta_FLE_corr_", hemi)]] <- 
      pse_wide[[paste0("FLE_corr_petal_", hemi)]] - pse_wide[[paste0("FLE_corr_fugal_", hemi)]]
    
    # Store individual components for analysis
    pse_wide[[paste0("motion_component_petal_", hemi)]] <- motion_component_petal
    pse_wide[[paste0("motion_component_fugal_", hemi)]] <- motion_component_fugal
    pse_wide[[paste0("flash_component_petal_", hemi)]] <- flash_component_petal
    pse_wide[[paste0("flash_component_fugal_", hemi)]] <- flash_component_fugal
  }
  
  participant_list[[subject_id]] <- pse_wide
}

# Combine all participants
all_data <- bind_rows(participant_list)

# =============================================================================
#                          SAVE OUTPUT
# =============================================================================

# Save wide format data
output_file <- file.path(data_dir, "E2_FLE_all_participants.csv")
write_csv(all_data, output_file)
cat(sprintf("\nSaved participant data to: %s\n", output_file))

# =============================================================================
#                          GROUP SUMMARY
# =============================================================================

cat("\n=== GROUP SUMMARY ===\n\n")

# Calculate group means for key measures
key_vars <- c(
  "FLE_raw_petal_upper", "FLE_raw_fugal_upper",
  "FLE_raw_petal_lower", "FLE_raw_fugal_lower",
  "FLE_corr_petal_upper", "FLE_corr_fugal_upper", 
  "FLE_corr_petal_lower", "FLE_corr_fugal_lower",
  "delta_FLE_raw_upper", "delta_FLE_raw_lower",
  "delta_FLE_corr_upper", "delta_FLE_corr_lower"
)

for (var in key_vars) {
  if (var %in% names(all_data)) {
    values <- all_data[[var]]
    if (sum(!is.na(values)) > 0) {
      cat(sprintf("%s: M = %.3f, SE = %.3f (n = %d)\n",
                  var, mean(values, na.rm = TRUE), ste(values), sum(!is.na(values))))
    }
  }
}

# =============================================================================
#                          BASIC PLOTS
# =============================================================================

# Create a simple plot if there's enough data
if (nrow(all_data) >= 1) {
  
  # Prepare data for plotting
  plot_data <- all_data %>%
    select(subject_id, starts_with("FLE_raw"), starts_with("FLE_corr")) %>%
    pivot_longer(
      cols = -subject_id,
      names_to = "measure",
      values_to = "value"
    ) %>%
    filter(!is.na(value)) %>%
    mutate(
      type = ifelse(grepl("raw", measure), "Raw", "Corrected"),
      direction = case_when(
        grepl("petal", measure) ~ "Petal",
        grepl("fugal", measure) ~ "Fugal",
        TRUE ~ NA_character_
      ),
      hemifield = case_when(
        grepl("upper", measure) ~ "Upper",
        grepl("lower", measure) ~ "Lower",
        TRUE ~ NA_character_
      )
    ) %>%
    filter(!is.na(direction), !is.na(hemifield))
  
  if (nrow(plot_data) > 0) {
    # Create summary for plot
    plot_summary <- plot_data %>%
      group_by(type, direction, hemifield) %>%
      summarise(
        mean = mean(value, na.rm = TRUE),
        se = ste(value),
        .groups = 'drop'
      )
    
    # Bar plot
    p <- ggplot(plot_summary, aes(x = direction, y = mean, fill = type)) +
      geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7) +
      geom_errorbar(
        aes(ymin = mean - se, ymax = mean + se),
        position = position_dodge(width = 0.8),
        width = 0.2
      ) +
      geom_hline(yintercept = 0, linetype = "dashed", color = "grey50") +
      facet_wrap(~hemifield) +
      labs(
        title = "Flash-Lag Effect by Motion Direction and Hemifield",
        x = "Motion Direction",
        y = "FLE Magnitude (DVA)",
        fill = "FLE Type"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "bottom"
      ) +
      scale_fill_manual(values = c("Raw" = "#4ECDC4", "Corrected" = "#FF6B6B"))
    
    # Save plot
    plot_file <- file.path(data_dir, "E2_FLE_summary_plot.png")
    ggsave(plot_file, p, width = 10, height = 6, dpi = 150)
    cat(sprintf("\nSaved plot to: %s\n", plot_file))
  }
}

cat("\n=== ANALYSIS COMPLETE ===\n")
