# =============================================================================
#                    FLASH GRAB EFFECT (FGE) PSE CALCULATION
#                         Last modified: November 5, 2025
# =============================================================================
#
# This script calculates Points of Subjective Equality (PSE) from FGE experiments
# using psychometric function fitting (logistic regression via GLM).
#
# INPUT: CSV files generated by FGE_orthogonal_3.m and FGE_radial_3.m
# OUTPUT: Wide-format CSV with PSEs for all conditions and derived measures

# =============================================================================
#                              LOAD LIBRARIES
# =============================================================================


# Load libraries
library(readr)
library(dplyr)
library(tidyr)

# =============================================================================
#                           CONFIGURATION
# =============================================================================

# Specify the directory containing CSV files
data_dir <- "/Users/jmar3294/Documents/MATLAB/FGE_UNIFORM_CONTROL/data"

# =============================================================================
#                        HELPER FUNCTIONS
# =============================================================================

# Function to fit psychometric function and extract PSE
fit_psychometric <- function(data) {
  # Check if we have enough data points
  if (nrow(data) < 3) {
    return(tibble(pse = NA, jnd = NA, n_trials = nrow(data)))
  }
  
  # Create binary response: 1 = "outer" response, 0 = "inner" response
  data <- data %>%
    mutate(response_binary = ifelse(response == "outer", 1, 0))
  
  # Fit logistic regression: P(outer) ~ probe_offset_dva
  tryCatch({
    model <- glm(response_binary ~ probe_offset_dva, 
                 family = binomial(logit), 
                 data = data)
    
    # Extract coefficients
    coefs <- coef(model)
    intercept <- coefs[1]
    slope <- coefs[2]
    
    # Calculate PSE: point where P(outer) = 0.5
    # PSE = -intercept / slope
    pse <- -intercept / slope
    
    # Calculate JND: log(3) / slope
    jnd <- log(3) / slope
    
    return(tibble(
      pse = pse,
      slope = slope,
      jnd = jnd,
      n_trials = nrow(data),
      model_converged = TRUE
    ))
  }, error = function(e) {
    return(tibble(
      pse = NA,
      slope = NA,
      jnd = NA,
      n_trials = nrow(data),
      model_converged = FALSE
    ))
  })
}

# =============================================================================
#                          READ AND PROCESS DATA
# =============================================================================

# List all CSV files matching the pattern
csv_files <- list.files(
  path = data_dir,
  pattern = "^\\d{3}_FGE_(O|R)_.*\\.csv$",
  full.names = TRUE
)

if (length(csv_files) == 0) {
  stop("No CSV files found in the specified directory!")
}

# Initialize list to store participant data
participant_list <- list()

# Loop through each CSV file
for (file_path in csv_files) {
  
  # Read data
  data <- read_csv(file_path, show_col_types = FALSE)
  
  # Extract participant ID and motion type from filename
  file_name <- basename(file_path)
  participant_id <- substr(file_name, 1, 3)
  
  # Determine motion type (O = Orthogonal, R = Radial)
  if (grepl("_FGE_O_", file_name)) {
    motion_type <- "O"
  } else if (grepl("_FGE_R_", file_name)) {
    motion_type <- "R"
  } else {
    next  # Skip if pattern doesn't match
  }
  
  # Filter valid trials only (exclude catch trials and invalid trials)
  valid_data <- data %>%
    filter(valid_trial == "valid") %>%
    filter(response %in% c("inner", "outer"))  # Exclude NaN responses
  
  if (nrow(valid_data) == 0) {
    warning(paste("No valid trials for participant", participant_id, "motion type", motion_type))
    next
  }
  
  # ==========================================================================
  #                    CALCULATE PSEs FOR ALL CONDITIONS
  # ==========================================================================
  
  # 1. Basic PSEs by motion direction (pooled across quadrants and eccentricities)
  basic_pses <- valid_data %>%
    group_by(motion_direction) %>%
    group_modify(~ fit_psychometric(.x)) %>%
    ungroup() %>%
    mutate(
      condition = paste0(
        case_when(
          motion_direction == "petal" ~ "Petal_PSE_",
          motion_direction == "fugal" ~ "Fugal_PSE_",
          motion_direction == "uniform_control" ~ "Control_PSE_"
        ),
        motion_type
      )
    ) %>%
    select(condition, pse)
  
  # Also extract slopes for basic conditions
  basic_slopes <- valid_data %>%
    group_by(motion_direction) %>%
    group_modify(~ fit_psychometric(.x)) %>%
    ungroup() %>%
    mutate(
      condition = paste0(
        case_when(
          motion_direction == "petal" ~ "Petal_Slope_",
          motion_direction == "fugal" ~ "Fugal_Slope_",
          motion_direction == "uniform_control" ~ "Control_Slope_"
        ),
        motion_type
      )
    ) %>%
    select(condition, slope) %>%
    rename(pse = slope)  # Rename for binding
  
  # 2. PSEs by left/right visual field
  leftright_pses <- valid_data %>%
    mutate(
      side = ifelse(quadrant %in% c("upper_left", "lower_left"), "Left", "Right")
    ) %>%
    group_by(motion_direction, side) %>%
    group_modify(~ fit_psychometric(.x)) %>%
    ungroup() %>%
    mutate(
      prefix = case_when(
        motion_direction == "petal" ~ "Petal",
        motion_direction == "fugal" ~ "Fugal",
        motion_direction == "uniform_control" ~ "Control"
      ),
      condition = paste0(prefix, "_PSE_", motion_type, "_", side)
    ) %>%
    select(condition, pse)
  
  # 3. PSEs by eccentricity (inner vs outer)
  eccentricity_pses <- valid_data %>%
    group_by(motion_direction, eccentricity) %>%
    group_modify(~ fit_psychometric(.x)) %>%
    ungroup() %>%
    mutate(
      prefix = case_when(
        motion_direction == "petal" ~ "Petal",
        motion_direction == "fugal" ~ "Fugal",
        motion_direction == "uniform_control" ~ "Control"
      ),
      ecc_label = ifelse(eccentricity == "inner", "Inner", "Outer"),
      condition = paste0(prefix, "_PSE_", motion_type, "_", ecc_label)
    ) %>%
    select(condition, pse)
  
  # 4. PSEs by upper/lower visual field
  upperlower_pses <- valid_data %>%
    mutate(
      vertical = ifelse(quadrant %in% c("upper_left", "upper_right"), "Upper", "Lower")
    ) %>%
    group_by(motion_direction, vertical) %>%
    group_modify(~ fit_psychometric(.x)) %>%
    ungroup() %>%
    mutate(
      prefix = case_when(
        motion_direction == "petal" ~ "Petal",
        motion_direction == "fugal" ~ "Fugal",
        motion_direction == "uniform_control" ~ "Control"
      ),
      condition = paste0(prefix, "_PSE_", motion_type, "_", vertical)
    ) %>%
    select(condition, pse)
  
  # Combine all PSE measurements
  all_pses <- bind_rows(
    basic_pses,
    basic_slopes,
    leftright_pses,
    eccentricity_pses,
    upperlower_pses
  )
  
  # Pivot to wide format
  pse_wide <- all_pses %>%
    pivot_wider(names_from = condition, values_from = pse)
  
  # Add participant ID
  pse_wide <- pse_wide %>%
    mutate(Participant_ID = participant_id, .before = 1)
  
  # Exclude specified participants
  if (participant_id %in% c("000", "001", "012", "666")) {
    cat("Excluding participant", participant_id, "\n")
    next
  }
  
  # Store in list
  participant_list[[paste0(participant_id, "_", motion_type)]] <- pse_wide
}

# =============================================================================
#                    COMBINE DATA ACROSS PARTICIPANTS
# =============================================================================

# Merge orthogonal (O) and radial (R) data for each participant
combined_data <- participant_list %>%
  bind_rows() %>%
  group_by(Participant_ID) %>%
  summarise(across(everything(), ~ first(na.omit(.))), .groups = "drop")

# =============================================================================
#                       CALCULATE DERIVED MEASURES
# =============================================================================

final_data <- combined_data %>%
  mutate(
    # Basic FGE: Motion - Control
    FGE_Petal_R = Petal_PSE_R - Control_PSE_R,
    FGE_Fugal_R = Fugal_PSE_R - Control_PSE_R,
    FGE_Petal_O = Petal_PSE_O - Control_PSE_O,
    FGE_Fugal_O = Fugal_PSE_O - Control_PSE_O,
    
    # Left/Right FGE
    FGE_Petal_R_Left = Petal_PSE_R_Left - Control_PSE_R_Left,
    FGE_Petal_R_Right = Petal_PSE_R_Right - Control_PSE_R_Right,
    FGE_Fugal_R_Left = Fugal_PSE_R_Left - Control_PSE_R_Left,
    FGE_Fugal_R_Right = Fugal_PSE_R_Right - Control_PSE_R_Right,
    FGE_Petal_O_Left = Petal_PSE_O_Left - Control_PSE_O_Left,
    FGE_Petal_O_Right = Petal_PSE_O_Right - Control_PSE_O_Right,
    FGE_Fugal_O_Left = Fugal_PSE_O_Left - Control_PSE_O_Left,
    FGE_Fugal_O_Right = Fugal_PSE_O_Right - Control_PSE_O_Right,
    
    # Upper/Lower FGE
    FGE_Petal_R_Upper = Petal_PSE_R_Upper - Control_PSE_R_Upper,
    FGE_Petal_R_Lower = Petal_PSE_R_Lower - Control_PSE_R_Lower,
    FGE_Fugal_R_Upper = Fugal_PSE_R_Upper - Control_PSE_R_Upper,
    FGE_Fugal_R_Lower = Fugal_PSE_R_Lower - Control_PSE_R_Lower,
    FGE_Petal_O_Upper = Petal_PSE_O_Upper - Control_PSE_O_Upper,
    FGE_Petal_O_Lower = Petal_PSE_O_Lower - Control_PSE_O_Lower,
    FGE_Fugal_O_Upper = Fugal_PSE_O_Upper - Control_PSE_O_Upper,
    FGE_Fugal_O_Lower = Fugal_PSE_O_Lower - Control_PSE_O_Lower,
    
    # Eccentricity FGE
    FGE_Petal_R_Inner = Petal_PSE_R_Inner - Control_PSE_R_Inner,
    FGE_Petal_R_Outer = Petal_PSE_R_Outer - Control_PSE_R_Outer,
    FGE_Fugal_R_Inner = Fugal_PSE_R_Inner - Control_PSE_R_Inner,
    FGE_Fugal_R_Outer = Fugal_PSE_R_Outer - Control_PSE_R_Outer,
    FGE_Petal_O_Inner = Petal_PSE_O_Inner - Control_PSE_O_Inner,
    FGE_Petal_O_Outer = Petal_PSE_O_Outer - Control_PSE_O_Outer,
    FGE_Fugal_O_Inner = Fugal_PSE_O_Inner - Control_PSE_O_Inner,
    FGE_Fugal_O_Outer = Fugal_PSE_O_Outer - Control_PSE_O_Outer
  )

# =============================================================================
#                           SAVE OUTPUT
# =============================================================================

# Create output filename with timestamp
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output_file <- file.path(data_dir, paste0("FGE_PSE_summary_", timestamp, ".csv"))

# Write to CSV
write_csv(final_data, output_file)

cat("\n=== PSE CALCULATION COMPLETE ===\n")
cat("Output saved to:", output_file, "\n")
cat("Total participants processed:", nrow(final_data), "\n")

# =============================================================================
#                           DISPLAY SUMMARY
# =============================================================================

cat("\n=== COLUMN SUMMARY ===\n")
cat("Columns in output:\n")
cat(paste(names(final_data), collapse = "\n"), "\n")
